name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    environment: prod
    env:
      SNOWSQL_USER: "${{ secrets.SNOWSQL_USER }}"
      SNOWSQL_PWD: "${{ secrets.SNOWSQL_PWD }}"
      SNOWSQL_DATABASE: "${{ secrets.SNOWSQL_DATABASE }}"
      SNOWSQL_ACCOUNT: "${{ secrets.SNOWSQL_ACCOUNT }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Set up
      run: bin/setup
  
    # We should exit 0 on deploys because we want to include some failing tests & models
    # for demo purposes. An improvement would be to write a script that checks
    # the only failing models & tests are the expected ones.
    - name: Deploy
      run: |
        bin/dbt build --target prod
