version: 2

sources:
  - name: snowflake
    database: snowflake
    schema: account_usage
    tables:
      - name: query_history

models:
  - name: fct_debby_query_history
  - name: fct_debby_model_runs
  - name: fct_debby_test_runs
  - name: dim_debby_test_status
  - name: dim_debby_model_status
